;METADATA=(Diff=true, UseCommands=true)
[/Script/TheIsle.TIGameSession]
ServerName=[SEA/VN] The Isle Viet Nam TEST
Discord=discord.gg
MapName=Gateway
MaxPlayerCount=200
bEnableHumans=false
bServerPassword=false
ServerPassword=
bServerWhitelist=true
bEnableGlobalChat=true
bQueueEnabled=true
QueuePort=10000
QueueJoinTimeoutSeconds=300
QueueHeartbeatIntervalSeconds=8
QueueHeartbeatTimeoutSeconds=5
QueueHeartbeatMaxMisses=6
bRconEnabled=true
RconPassword=admin1@
RconPort=8888
bRandomWeatherEnabled=true
MinWeatherVariationInterval=600
MaxWeatherVariationInterval=900
ServerDayLengthMinutes=45
ServerNightLengthMinutes=16
bSpawnPlants=true
PlantSpawnMultiplier=1
bSpawnAI=true
AISpawnInterval=40
AIDensity=1.2
GrowthMultiplier=1
bEnableDiets=true
bEnableMutations=true
bEnableMigration=true
MaxMigrationTime=5400
SpeciesMigrationTime=10800
bEnableMassMigration=true
MassMigrationTime=43200
MassMigrationDisableTime=7200
bEnablePatrolZones=true
bUseRegionSpawning=true
bUseRegionSpawnCooldown=true
RegionSpawnCooldownTimeSeconds=600
CorpseDecayMultiplier=2
bAllowRecordingReplay=true

[/Script/TheIsle.TIGameStateBase]
AdminsSteamIDs=76561198850624000
WhitelistIDs=
VIPs=
AllowedClasses=Allosaurus
AllowedClasses=Austroraptor
AllowedClasses=Beipiaosaurus
AllowedClasses=Carnotaurus
AllowedClasses=Ceratosaurus
AllowedClasses=Deinosuchus
AllowedClasses=Diabloceratops
AllowedClasses=Dilophosaurus
AllowedClasses=Dryosaurus
AllowedClasses=Gallimimus
AllowedClasses=Herrerasaurus
AllowedClasses=Hypsilophodon
AllowedClasses=Kentrosaurus
AllowedClasses=Maiasaura
AllowedClasses=Omniraptor
AllowedClasses=Pachycephalosaurus
AllowedClasses=Pteranodon
AllowedClasses=Stegosaurus
AllowedClasses=Tenontosaurus
AllowedClasses=Triceratops
AllowedClasses=Troodon
AllowedClasses=Tyrannosaurus

